version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/jobdb
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
